config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home, only: :index
  resources :users do
    resources :posts
  end
  resources :sessions

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'

  # match '/users/:user_id/posts/new', :to => 'posts#create', :via => [:post]

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  validates :title, :date, :calories, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save { self.email = email.downcase }

  has_many :posts, class_name: 'Post', foreign_key: "creator_id"

  validates :first_name,:last_name, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  #
  # def edit
  #   @post = Post.find(params[:id])
  # end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end
  #
  # def update
  #   @post = Post.find(params[:id])
  #
  #   if @post.update(article_params)
  #     redirect_to @post
  #   else
  #     render 'edit'
  #   end
  # end

  def show
    @post = Post.find(params[:id])
  end

  # def index
  #   @post = Post.all
  # end
  #
  # def destroy
  #   @post = Post.find(params[:id])
  #   @post.destroy
  #
  #   redirect_to post_path
  # end

  private
  def post_params
    params.permit(:title, :date, :calories, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      log_in(@user)
      redirect_to root_path
    else
      redirect_to '/register'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)

      if @user.save
        log_in @user
        redirect_to root_path
      else
        render :new
      end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      nil
    end
  end

  def authorize
    redirect_to login_path unless current_user
  end
end

app/views/home/index.html.erb
<% if current_user %>
  <h1 class="title_web">Hello, <%= current_user.first_name %> <%= current_user.last_name %>!</h1>
<% else %>
  <h1 class="title_web">Welcome to Workout Buddy</h1>
<% end %>

<p class="welcome">
  Workout Buddy is a place to log in your workouts, in a simple and friendly way. Log in with the the ability to have your own personal journal on the web. Log your thoughts, and the period of time you worked out. Also have the ability to listen to music while you enter your information. 
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutBuddy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>
    <header>
      <% if current_user %>
        <!-- <div class="nav">
          <h3 id="username"><%= current_user.email %><h3>
          <%= link_to "Logout", '/logout', class: "btn btn-default" %>
          <%= link_to "Home", root_path , class: "btn btn-default" %>
        </div> -->
        <div class="topnav" id="myTopnav">
          <a><%= link_to current_user.email, user_path(@user) %></a>
          <a><%= link_to "Logout", '/logout' %></a>
          <a><%= link_to "Home", root_path %></a>
        </div>
      <% else %>
        <!-- <div class="nav">
          <%= link_to "Login", login_path, class: "btn btn-default" %>
          <%= link_to "Register", register_path, class: "btn btn-default" %>
          <%= link_to "Home", root_path, class: "btn btn-default" %>
        </div> -->
        <div class="topnav" id="myTopnav">
          <a><%= link_to "Login", login_path %></a>
          <a><%= link_to "Register", register_path %></a>
          <a><%= link_to "Home", root_path %></a>
        </div>
      <% end %>

    </header>

  <body class="body">
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

  <%= f.label :title, class: "form-group" %>
  <%= f.text_field :title, placeholder: 'Title', class: "form-control" %>

  <%= f.label :date, class: "form-group" %>
  <%= f.date_field :date, placeholder: 'Date', class: "form-control" %>

  <%= f.label :calories, class: "form-group" %>
  <%= f.number_field :calories, placeholder: 'Calories', class: "form-control" %>

  <%= f.label :description, class: "form-group" %>
  <%= f.text_area :description, :cols => 30, :rows => 10, placeholder: 'Description', class: "form-control" %><br>

  <%= f.submit "Log Workout", class: "btn btn-success" %>
<% end %>

app/views/users/new.html.erb
<h1 class="title_web">Workout Buddy: User Registration</h1><br>

<%= form_for @user do |f| %>

  <%= f.label :first_name, class: "form-group" %>
  <%= f.text_field :first_name, placeholder: 'First Name', class: "form-control" %>

  <%= f.label :last_name, class: "form-group" %>
  <%= f.text_field :last_name, placeholder: 'Last Name', class: "form-control" %>

  <%= f.label :email, class: "form-group" %>
  <%= f.text_field :email, placeholder: 'Email', class: "form-control" %>

  <%= f.label :password, class: "form-group" %>
  <%= f.password_field :password, placeholder: 'Password', class: "form-control" %>

  <%= f.label :password_confirmation, class: "form-group" %>
  <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: "form-control"%><br>


  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/users/show.html.erb
<h1 class="title_web">Welcome back <%= current_user.first_name %> <%= current_user.last_name %></h1>

<a><%= link_to "Log Workout", "/users/#{current_user.id}/posts/new", class: "btn btn-primary" %></a>

<% if @posts%>